#### 1. EMail Generator
* Write a function to take First Name, Last Name and Date of Birth as input from the user and generate an EMail ID for them.
* The function should return the email id as <br>First two letters of First Name,<br>followed by First letter of Last Name,<br>followed by DOB without '/' followed by '@xyz.com'
* For Eg: **First Name:** Alice , **Last Name:** Garner , **DOB:** 07/11/1995
* Eg Output: alg07111995@xyz.com

In [42]:
a = input(" Enter First Name:")
b = input(" Enter Last Name: ")
c = input(" Enter DOB: ")

l = c.split("/")
z = "@xyz.com"

a1 = a[0] +a[1]+b[0] +l[0]+l[1]+l[2]+z[0]+z[1]+z[2]+z[3]+z[4]+z[5]+z[6]+z[7]
print(a1)

 Enter First Name:taral
 Enter Last Name: sarvagod
 Enter DOB: 13/04/1998
tas13041998@xyz.com


#### 2. Brightness Adjustments

* Intuition: Let us say you have a grayscale image matrix of dimension 3x3<br>[150, 23, 21]<br>[168, 145, 23]<br>[170, 163, 150]<br>we need to reduce the brightness of this image by a factor of 10 i.e. each element of the image matrix should be subtracted by 10. Thus giving us the output image matrix as <br>[140, 13, 11]<br>[158, 135, 13]<br>[160, 153, 140]
* Create a 3x3 matrix having random values between the range of 0 to 255.
* Create a 3x3 matrix having all elements as 10.
* Reduce (Subtraction) the brightness matrix from the image matrix.

In [10]:
import numpy as np

a = np.random.randint( low = 255, size =(3,3))
print("The first matrix: \n",a,"\n\n")
b = np.full((3,3) , 10)
print("The second matrix: \n",b,"\n\n")

c = np.subtract(a,b)
print("The result matrix: \n",c)

The first matrix: 
 [[254  66 187]
 [ 44 108 114]
 [231 190 197]] 


The second matrix: 
 [[10 10 10]
 [10 10 10]
 [10 10 10]] 


The result matrix: 
 [[244  56 177]
 [ 34  98 104]
 [221 180 187]]


#### 3. Central Tendency Test

* Intuition: Our goal here is to check the skewness of our distribution.
* Skewness
    * Positively Skewed : Mean > Median
    * Negetively Skewed : Mean < Median
    * Normal Curve : Mean = Median
* Write a function that takes an array of 9 numbers as input and returns the skewness of its distribution.
* Try your function for these inputs
    * Input: [1,2,3,4,5,6,7,8,9] , Expected Output: "Normal Curve"
    * Input: [1,2,3,4,5,6,9,9,10] , Expected Output: "Positively Skewed"
    * Input: [1,1,1,4,5,6,7,8,9] , Expected Output: "Negatively Skewed"
* **Note:** For this test consider the distribution to be sorted in an ascending order. Write code in such a way that even if unsorted array is passed as an input it handles it correctly.

In [40]:

a = []

for i in range(9):
    x = int(input(" Enter 9 n0s: "))
    a.append(x)
a1 = a.sort()

print("Your List: ",a)


m = 0
for i in range(9):
    m = m + a[i]
    
mean = m/9
print("\n Mean: ",mean)

median = a[4]
print("\n Median:",median)

if mean > median:
    print("\n Positively Skewed")

elif median > mean:
    print("\n Negatively Skewed")

else:
    print("\n Normal curve")



 Enter 9 n0s: 5
 Enter 9 n0s: 4
 Enter 9 n0s: 5
 Enter 9 n0s: 7
 Enter 9 n0s: 8
 Enter 9 n0s: 6
 Enter 9 n0s: 5
 Enter 9 n0s: 4
 Enter 9 n0s: 2
Your List:  [2, 4, 4, 5, 5, 5, 6, 7, 8]

 Mean:  5.111111111111111

 Median: 5

 Positively Skewed


#### 4. Calculating Distances

* Below are two equations for calculating distances between 2 points
    * Euclidean Distance : $\sqrt{(x2 - x1)^2 + (y2-y1)^2}$
    * Manhattan Distance : $ |x2-x1| + |y2-y1| $
* Write a function that takes the x and y coordiantes for two points as inputs and returns the Euclidean and Manhattan distance between the two.

In [43]:
a = []

for i in range(2):
    x = int(input(" Enter x1 and y1: "))
    a.append(x)
    
b = []

for i in range(2):
    y = int(input(" Enter x2 and y2: "))
    b.append(y)
    
def distance(m,n):
    e = (((n[0]-m[0])**2) + ((n[1]-m[1])**2))**1/2
    print("Eucledian Distance: ",e)
    
    h = abs(n[0]-m[0]) + abs(n[1]-m[1])
    print("Manhattan Distance: ",h)
    
distance(a,b)

    

 Enter x1 and y1: 5
 Enter x1 and y1: 4
 Enter x2 and y2: 6
 Enter x2 and y2: 8
Eucledian Distance:  8.5
Manhattan Distance:  5


#### 5. Softmax Function

* The Softmax Function : $ \frac{e^x}{\sum{e^x}} $
* Create a function that takes a array of numbers as input and returns the probabilities of each element of that array.
* Eg: 
    * Input : [1,2,3]
    * Denominator : e^1 + e^2 + e^3 = 2.71 + 7.38 + 20.08 = 30.16
    * Softmax for each element:
        * e^1/30.16 = 0.089
        * e^2/30.16 = 0.244
        * e^3/30.16 = 0.665

In [ ]:
n = int(input(" Enter numbers to be added"))
a = []
for i in range(n):
    x = int(input(" Enter nos: "))
    a.append(x)
    
    

def softmax(k):
    for i in range(k):
        
        
    